name: CI Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'  # Set up Python 3.11 (you can change to any version like 3.10, 3.9, etc.)

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Use pip to install dependencies for Python 3

      - name: Run tests
        run: |
          python -m unittest discover  # Run tests using Python 3
